### ISSUE TITLE
pygame.error: No available video device

### ISSUE THREAD

**Issue by bobvanluijt** [255BITS/HyperGAN#123]
After training I'm getting the below output, is it possible to disable pygame? I'm training in the cloud so I don't have a video device available. Thx

```
\ 0:  d_loss 0.22 g_loss 0.50
Traceback (most recent call last):
  File "/usr/local/bin/hypergan", line 122, in <module>
    gancli.run()
  File "/usr/local/lib/python3.5/dist-packages/hypergan/cli.py", line 198, in run
    self.train()
  File "/usr/local/lib/python3.5/dist-packages/hypergan/cli.py", line 143, in train
    self.step()
  File "/usr/local/lib/python3.5/dist-packages/hypergan/cli.py", line 102, in step
    sample_list = self.sample(sample_file)
  File "/usr/local/lib/python3.5/dist-packages/hypergan/cli.py", line 87, in sample
    sample_list = self.sampler.sample(sample_file, self.args.save_samples)
  File "/usr/local/lib/python3.5/dist-packages/hypergan/samplers/base_sampler.py", line 29, in sample
    return [{'image':path, 'label':'sample'} for sample_data, sample_filename in samples]
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3812, in get_controller
    yield default
  File "/usr/local/lib/python3.5/dist-packages/hypergan/samplers/base_sampler.py", line 25, in sample
    self.plot(sample_data, path, save_samples)
  File "/usr/local/lib/python3.5/dist-packages/hypergan/samplers/base_sampler.py", line 46, in plot
    GlobalViewer.update(image)
  File "/usr/local/lib/python3.5/dist-packages/hypergan/pygame_viewer.py", line 26, in update
    self.screen = self.pg.display.set_mode(size)
pygame.error: No available video device
```

**Comment by martyn** [comment]
Hi, you can disable the ui with `--noviewer`

**Comment by bobvanluijt** [comment]
Thx mate
