### ISSUE TITLE
Error in __init__.py

### ISSUE THREAD

**Issue by veqtor** [255BITS/HyperGAN#14]
I get this output:

hypergan train ~/hgan_dataset/ -f jpg -b 8 --config hej --device '/cpu:0'
[hypergan] Welcome back.  You are one of  27000000000000  possible configurations.
Traceback (most recent call last):
  File "/Users/goransandstrom/anaconda/bin/hypergan", line 5, in <module>
    run(args)
  File "/Users/goransandstrom/anaconda/lib/python3.5/site-packages/hypergan/__init__.py", line 311, in run
    other_config = copy.copy(config)
  File "/Users/goransandstrom/anaconda/lib/python3.5/copy.py", line 97, in copy
    rv = reductor(4)
TypeError: 'NoneType' object is not callable

**Comment by martyn** [comment]
Hey, thanks for the bug report.  I found the problem and published a fix.  Upgrade with:

```python
  pip3 install hypergan --upgrade
```
