### ISSUE TITLE
Default configurations may be unstable

### ISSUE THREAD

**Issue by martyn** [255BITS/HyperGAN#50]
Default configurations may diverge.

When a configuration is created it is set to random values within a predefined range.  That range has some bad areas at the moment.

Until this is fixed see `examples/configs` for stable configs

**Comment by mikkel** [comment]
This has been fixed in 0.8.4

**Comment by martyn** [comment]
This has been defaulted to `lsgan` with `rmsprop`, which is the configuration used in the samples.  If this is still not converging let us know!

If upgrading:  You will need to remove/rename your configuration file before running again.

**Comment by ProGamerGov** [comment]
@martyn Using the `rmsprop-lsgan.json` config, and a size of 128x128, the model appeared to be training correctly until things completely collapsed at 70000 iterations. It was actually creating a diverse bunch of extremely realistic looking images right before what I think is called "mode collapse"?  

This is the second time I've had this issue with  `rmsprop-lsgan.json` and `-size 128x128`.

I can upload the video made from the sample images, if you need that.

**Comment by mikkel** [comment]
Hi, thanks for letting us know about this.  We've been working off the #66 and it has a few tricks that seem to help avoid this.

The first is hypergan can now replicate paper results using the `-c <config>` flag.  The documentation is pretty sparse atm, but it loads up configs found in this directory: https://github.com/255BITS/HyperGAN/tree/develop/hypergan/configurations

The second is an optional argument called `--autoencode` which adds reconstruction loss.  It seems to stabilize training at the cost of conditional averaging.  AlphaGAN #101 may help with the conditional averaging .

`python3 setup.py develop` links everything if you decide to run `develop`.

**Comment by ProGamerGov** [comment]
@mikkel For the [development mode](https://github.com/255BITS/HyperGAN#development-mode), do I have to clone the `develop` branch? Or does `python3 setup.py develop` handle that?

**Comment by ProGamerGov** [comment]
The `develop` branch seems to throw out errors similar to this for all the config options: 

```
ubuntu@ip-Address:~$ LD_PRELOAD="/usr/lib/libtcmalloc.so.4" hypergan train faceGAN/data/faces -s 64x64x3 -f png -b 32 --sampler began -c began --sample_every 5 --save_every 1000
[loader] ImageLoader found 2390 images with 2 different class labels
lookup failed for   https://arxiv.org/abs/1703.10717
lookup failed for   Boundary Equilibrium GAN.  Uses an internal autoencoder
lookup failed for   wgan
2017-06-23 01:32:10.844488: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-23 01:32:10.844533: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-23 01:32:10.844543: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-06-23 01:32:10.844555: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-23 01:32:10.844566: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-06-23 01:32:13.807840: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:893] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-06-23 01:32:13.808364: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 0 with properties:
name: Tesla K80
major: 3 minor: 7 memoryClockRate (GHz) 0.8235
pciBusID 0000:00:1e.0
Total memory: 11.17GiB
Free memory: 11.11GiB
2017-06-23 01:32:13.808392: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0
2017-06-23 01:32:13.808403: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   Y
2017-06-23 01:32:13.808426: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K80, pci bus id: 0000:00:1e.0)
[dcgan] NET IS Tensor("concat:0", shape=(32, 100), dtype=float32, device=/device:GPU:0)
LINEAR shape is [32, 100]
w is  Tensor("concat:0", shape=(32, 100), dtype=float32, device=/device:GPU:0) <tf.Variable '1/w:0' shape=(100, 16384) dtype=float32_ref> <tf.Variable '1/b:0' shape=(16384,) dtype=float32_ref>
XG Tensor("shuffle_batch:0", shape=(32, 64, 64, 3), dtype=float32) Tensor("Tanh:0", shape=(32, 64, 64, 3), dtype=float32, device=/device:GPU:0)
GAN {'generator': {'activation': <function selu at 0x7f959c0f52f0>, 'class': <class 'hypergan.generators.dcgan_generator.DCGANGenerator'>}, 'publication': 'https://arxiv.org/abs/1703.10717', 'discriminator': {'final_features': 300, 'activation': <function selu at 0x7f959c0f52f0>, 'distance': <function l1_distance at 0x7f959c0f5a60>, 'improved': True, 'encoder': <class 'hypergan.discriminators.dcgan_discriminator.DCGANDiscriminator'>, 'class': <class 'hypergan.discriminators.autoencoder_discriminator.AutoencoderDiscriminator'>, 'decoder': <class 'hypergan.generators.dcgan_generator.DCGANGenerator'>}, 'encoder': {'max': 1, 'projections': [<function identity at 0x7f95b30686a8>], 'z': 100, 'class': <class 'hypergan.encoders.uniform_encoder.UniformEncoder'>, 'min': -1}, 'description': 'Boundary Equilibrium GAN.  Uses an internal autoencoder', 'loss': {'type': 'wgan', 'k_lambda': 0.01, 'use_k': True, 'gamma': 0.5, 'initial_k': 0.001, 'class': <class 'hypergan.losses.boundary_equilibrium_loss.BoundaryEquilibriumLoss'>, 'reduce': <function reduce_mean at 0x7f95b383f8c8>}, 'trainer': {'d_beta2': 0.99, 'anneal_learning_rate': True, 'g_beta1': 0.5, 'anneal_lower_bound': 2e-06, 'g_beta2': 0.99, 'd_learn_rate': 8e-05, 'd_beta1': 0.5, 'class': <class 'hypergan.trainers.alternating_trainer.AlternatingTrainer'>, 'g_trainer': <class 'tensorflow.python.training.adam.AdamOptimizer'>, 'g_learn_rate': 8e-05, 'd_trainer': <class 'tensorflow.python.training.adam.AdamOptimizer'>}}
LINEAR shape is [64, 8192]
w is  Tensor("Reshape_2:0", shape=(64, 8192), dtype=float32, device=/device:GPU:0) <tf.Variable 'autoencoder-d_5/w:0' shape=(8192, 300) dtype=float32_ref> <tf.Variable 'autoencoder-d_5/b:0' shape=(300,) dtype=float32_ref>
[dcgan] NET IS Tensor("mul_17:0", shape=(64, 300), dtype=float32, device=/device:GPU:0)
LINEAR shape is [64, 300]
w is  Tensor("mul_17:0", shape=(64, 300), dtype=float32, device=/device:GPU:0) <tf.Variable 'autoencoder-g_6/w:0' shape=(300, 16384) dtype=float32_ref> <tf.Variable 'autoencoder-g_6/b:0' shape=(16384,) dtype=float32_ref>
[autoencoder discriminator] hidden layer  Tensor("mul_17:0", shape=(64, 300), dtype=float32, device=/device:GPU:0)
lookup failed for   wgan
Traceback (most recent call last):
  File "/usr/local/bin/hypergan", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/ubuntu/hypergan/bin/hypergan", line 112, in <module>
    gancli.run()
  File "/home/ubuntu/hypergan/hypergan/cli.py", line 227, in run
    self.add_supervised_loss(gan)
NameError: name 'gan' is not defined
ubuntu@ip-Address:~$

```

**Comment by martyn** [comment]
I'm not sure where this was at, but 0.9 has been released to master(pip).  It might fix this issue. 
 Although `default` isn't completely stable, there are multiple configurations to choose from now.

**Comment by martyn** [comment]
I'm going to close this, feel free to open a new one if things are still broken(too much to read in this ticket :))
