### ISSUE TITLE
--crop does not work in 0.8

### ISSUE THREAD

**Issue by martyn** [255BITS/HyperGAN#60]
```bash
> hypergan train . -c 64 --device '/cpu:0' --crop                                                                                                                      
[hypergan] Welcome.  This is one of  1  possible configurations.
[hypergan] Config file /Users/martyn/.hypergan/configs/64.json
[loader] ImageLoader found 19 images with 28 different class labels
Traceback (most recent call last):
  File "/usr/local/bin/hypergan", line 8, in <module>
    cli.CLI()
  File "/usr/local/lib/python3.5/site-packages/hypergan/cli.py", line 22, in __init__
    self.run()
  File "/usr/local/lib/python3.5/site-packages/hypergan/cli.py", line 259, in run
    crop=crop
  File "/usr/local/lib/python3.5/site-packages/hypergan/cli.py", line 191, in setup_input_graph
    channels=channels)
  File "/usr/local/lib/python3.5/site-packages/hypergan/cli.py", line 220, in setup_input_loader
    height=height)
  File "/usr/local/lib/python3.5/site-packages/hypergan/loaders/image_loader.py", line 55, in labelled_image_tensors_from_directory
    height, width, dynamic_shape=True)
  File "/usr/local/lib/python3.5/site-packages/hypergan/loaders/resize_image_patch.py", line 163, in resize_image_with_crop_or_pad
    original_height, original_width, _ =     _ImageDimensions(image, dynamic_shape=dynamic_shape)
  File "/usr/local/lib/python3.5/site-packages/hypergan/loaders/resize_image_patch.py", line 222, in _ImageDimensions
    return array_ops.unpack(array_ops.shape(images))
AttributeError: module 'tensorflow.python.ops.array_ops' has no attribute 'unpack'
```

Originally reported in #55

**Comment by martyn** [comment]
Fixed and released(0.8.8).
