### ISSUE TITLE
No images found in directory

### ISSUE THREAD

**Issue by nkutsche155** [255BITS/HyperGAN#83]
When using the command "hypergan serve img_align_celeba_png/ -s 32x32x3 -f png -b 32 --config 123456" no images are found in my directory "img_align_celeba_png", although there are images.

Traceback (most recent call last):
  File "/usr/local/bin/hypergan", line 8, in <module>
    cli.CLI()
  File "/usr/local/lib/python3.5/dist-packages/hypergan/cli.py", line 22, in __init__
    self.run()
  File "/usr/local/lib/python3.5/dist-packages/hypergan/cli.py", line 259, in run
    crop=crop
  File "/usr/local/lib/python3.5/dist-packages/hypergan/cli.py", line 191, in setup_input_graph
    channels=channels)
  File "/usr/local/lib/python3.5/dist-packages/hypergan/cli.py", line 220, in setup_input_loader
    height=height)
  File "/usr/local/lib/python3.5/dist-packages/hypergan/loaders/image_loader.py", line 21, in labelled_image_tensors_from_directory
    assert len(filenames)!=0, "No images found in "+directory
AssertionError: No images found in img_align_celeba_png/

**Comment by martyn** [comment]
Is your directory 1 level deep?

img_align_celeba_png/img/1.png

The path to a file should look something like that, where 'img' can be any subdirectory name.

**Comment by ProGamerGov** [comment]
@martyn That doesn't fix the issue.

**Comment by ProGamerGov** [comment]
@nkutsche155 I figured out the issue here: https://github.com/255BITS/HyperGAN/issues/86#issuecomment-307492289

**Comment by martyn** [comment]
Thanks for the update.  I'm closing this issue since 0.9 is much more robust to input.
